### ISSUE TITLE
Firefox hotfix

### ISSUE THREAD

**Issue by alexeiva** [cyrealtype/Federant#1]
Dave, I added ttx files for these problematic fonts:
https://github.com/cyrealtype/Adamina
https://github.com/cyrealtype/Federant
https://github.com/cyrealtype/Alike

Didn't find a way to fix this issue myself.

**Comment by davelab6** [comment]
I've rebuilt with Glyphs and made pull requests for all 3 so closing this :) Thanks!

**Comment by alexeiva** [comment]
Federo needs an update too. 
https://github.com/cyrealtype/Federo

ofl/federo/Federo-Regular.ttf
ERROR: kern: Too large subtable, table discarded

**Comment by davelab6** [comment]
Lets track this on the Federo repo; it isn't urgent because it won't stop the font working, as these families errors did
